export const QUERY_KEY = {
  GET_UNREAD_NOTIFICATIONS: "GET_UNREAD_NOTIFICATIONS",
  GET_NOTIFICATIONS: "GET_NOTIFICATIONS",
  GET_NOTIFICATION_DETAILS: "GET_NOTIFICATION_DETAILS",
  MARK_NOTIFICATION_AS_READ: "MARK_NOTIFICATION_AS_READ",
  MARK_ALL_NOTIFICATIONS_AS_READ: "MARK_ALL_NOTIFICATIONS_AS_READ",
  MARK_NOTIFICATION_AS_UNREAD: "MARK_NOTIFICATION_AS_UNREAD"
}
