export enum NotificationReferenceType {
  // User types
  USER_PROFILE_DETAILS = "USER_PROFILE_DETAILS",
  USER_LIST = "USER_LIST",
  USER_ACCEPTED_INVITATION = "USER_ACCEPTED_INVITATION",

  // Loan application types for applicant
  LOAN_APPLICATION_LIST = "LOAN_APPLICATION_LIST",
  LOAN_APPLICATION_DETAILS = "LOAN_APPLICATION_DETAILS",

  // Loan application review types for loan officer
  LOAN_APPLICATION_REVIEW = "LOAN_APPLICATION_REVIEW",
  LOAN_APPLICATION_REVIEW_BUSINESS_VERIFICATION = "LOAN_APPLICATION_REVIEW_BUSINESS_VERIFICATION",
  LOAN_APPLICATION_REVIEW_DOCUMENT = "LOAN_APPLICATION_REVIEW_DOCUMENT",
  LOAN_APPLICATION_REVIEW_CASH_FLOW = "LOAN_APPLICATION_REVIEW_CASH_FLOW",
  LOAN_APPLICATION_REVIEW_LOAN_SUMMARY = "LOAN_APPLICATION_REVIEW_LOAN_SUMMARY",
  LOAN_APPLICATION_REVIEW_LOAN_DECISION = "LOAN_APPLICATION_REVIEW_LOAN_DECISION",

  // Loan Program types for CDFI Admin
  LOAN_PROGRAM_LIST = "LOAN_PROGRAM_LIST",
  LOAN_PROGRAM_DETAILS = "LOAN_PROGRAM_DETAILS",

  // Message types
  MESSAGE_LIST = "MESSAGE_LIST",
  MESSAGE_CONVERSATION = "MESSAGE_CONVERSATION",

  UNKNOWN = "UNKNOWN"
}

export enum NotificationType {
  SUCCESS = "SUCCESS",
  ERROR = "ERROR",
  WARNING = "WARNING",
  INFO = "INFO",
  UNKNOWN = "UNKNOWN"
}

export interface Notification {
  id: string
  userId: string
  subject: string
  content: string
  type?: NotificationType
  referenceType?: NotificationReferenceType
  referenceId?: string
  isRead: boolean
  createdAt: string
}
