export const QUERY_KEY = {
  GET_CC_OPERATING_EXPENSES_FORM: "GET_CC_OPERATING_EXPENSES_FORM",
  GET_CC_DIRECT_COSTS_FORM: "GET_CC_DIRECT_COSTS_FORM",
  GET_CC_CURRENT_ASSETS_FORM: "GET_CC_CURRENT_ASSETS_FORM",
  GET_CC_DEBT_FINANCING_FORM: "GET_CC_FP_DEBT_FINANCING_FORM"
}
