import cyphrLogo from "@/assets/logo-cyphr.jpg"
import { Separator } from "@/components/ui/separator"
import { cn } from "@/lib/utils"
import { Image } from "@/shared/atoms/Image"
import { FC } from "react"

interface DisclaimerNoteProps {
  companyName: string
  title?: string
  marginClass?: string
}

export const DisclaimerNote: FC<DisclaimerNoteProps> = (props) => {
  const { companyName, title, marginClass } = props

  return (
    <div className="flex flex-col justify-between gap-y-2xl p-[72px]">
      <Image
        src={cyphrLogo}
        placeholderClassName="bg-slate-400 rounded"
        alt="Institution text logo"
        height={90}
        width={360}
      />

      <p className={cn("text-6xl font-semibold mt-[1024px]", marginClass)}>
        {companyName}
      </p>
      <p className="text-2xl font-normal">{title ?? "Financial Forecast"}</p>
      <Separator />
      <div className="font-light text-xl text-justify flex flex-col gap-5">
        <p className="font-semibold">Disclaimer:</p>
        <p>
          The projections and financial statements provided in this application
          are generated based on user inputs, data retrieved from banking
          sources, and other third-party data providers. Please be advised that
          these projections are forward-looking and subject to uncertainties.
          Actual results may differ materially from the projections provided,
          and no guarantee of future performance is implied.
        </p>
        <p>
          All information is provided "as is," with no guarantees of
          completeness, accuracy, or timeliness. We are not responsible for any
          errors or omissions in the information or for the results obtained
          from its use. The financial projections are estimates and should be
          used as planning tools rather than definitive representations of your
          financial future.
        </p>
        <p>
          Our platform incorporates third-party data, and while we strive to
          ensure its accuracy, we do not assume any responsibility for
          inaccuracies or delays from external data providers. Users are
          encouraged to consult a financial professional before making decisions
          based on the projections generated by this application.
        </p>
        <p>
          We take the privacy of your data seriously. Please refer to our
          Privacy Policy for details on how your information is collected and
          used. By using this application, you acknowledge and agree to these
          terms.
        </p>
      </div>
    </div>
  )
}
