export const APP_CONFIGS = {
  API_BASE_URL: import.meta.env.VITE_API_ENDPOINT,
  FIREBASE_API_KEY: import.meta.env.VITE_FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID: import.meta.env.VITE_FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID: import.meta.env
    .VITE_FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID: import.meta.env.VITE_FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID: import.meta.env.VITE_FIREBASE_MEASUREMENT_ID,
  VITE_PUBLIC_ENDPOINT: import.meta.env.VITE_PUBLIC_ENDPOINT,
  VITE_BASE_SUBDOMAIN: import.meta.env.VITE_BASE_SUBDOMAIN ?? "capsight",
  VITE_PERSONA_ENVIRONMENT: import.meta.env.VITE_PERSONA_ENVIRONMENT,
  VITE_STYTCH_PUBLIC_TOKEN_DEV: import.meta.env.VITE_STYTCH_PUBLIC_TOKEN_DEV
}
