export enum FEATURE_FLAGS {
  SUBSCRIPTION_MANAGEMENT = "SUBSCRIPTION_MANAGEMENT",
  DOWNLOAD_CSV_AND_JSON_SUMMARY = "DOWNLOAD_CSV_AND_JSON_SUMMARY",
  IGNORE_KYC_SUBMISSION = "IGNORE_KYC_SUBMISSION",
  IGNORE_CASHFLOW_SUBMISSION = "IGNORE_CASHFLOW_SUBMISSION",
  LOAN_PROGRAM_FORMS_CONFIGURATION = "LOAN_PROGRAM_FORMS_CONFIGURATION",
  KYB_V2 = "KYB_V2",
  MULTI_FACTOR_AUTHENTICATION = "MULTI_FACTOR_AUTHENTICATION",
  MULTI_FACTOR_AUTHENTICATION_ADMIN_PORTAL = "MULTI_FACTOR_AUTHENTICATION_ADMIN_PORTAL",
  MULTI_FACTOR_AUTHENTICATION_LAUNCHKC = "MULTI_FACTOR_AUTHENTICATION_LAUNCHKC",
  PANDA_DOC_ESIGN_V1 = "PANDA_DOC_ESIGN_V1",
  GOOGLE_MAP_INPUT = "GOOGLE_MAP_INPUT",
  LOAN_PROGRAM_CHANGES_MANAGEMENT = "LOAN_PROGRAM_CHANGES_MANAGEMENT",
  CHAT_SUPPORT = "CHAT_SUPPORT",

  /**
   * Loan Ready V2
   */
  LOAN_READY_V2 = "LOAN_READY_V2",

  FORM_V2 = "FORM_V2",

  KCCHAMBER_PERSONA_KYC_DISABLED = "KCCHAMBER_PERSONA_KYC_DISABLED",

  /**
   * HISTORICAL_FINANCIALS_ENRICHMENT
   */
  HISTORICAL_FINANCIALS_ENRICHMENT = "HISTORICAL_FINANCIALS_ENRICHMENT"
}
