export enum FEATURE_FLAGS {
  SUBSCRIPTION_MANAGEMENT = "SUBSCRIPTION_MANAGEMENT",
  LENDER_DASHBOARD_V2 = "LENDER_DASHBOARD_V2",
  CASH_FLOW_V2 = "CASH_FLOW_V2",
  CASH_FLOW_V2_DUMMY_DATA = "CASH_FLOW_V2_DUMMY_DATA",
  PERSONA_KYC_V1 = "PERSONA_KYC_V1",
  LENDER_DASHBOARD_V2_DUMMY_DATA = "LENDER_DASHBOARD_V2_DUMMY_DATA"
}
