export enum FEATURE_FLAGS {
  SUBSCRIPTION_MANAGEMENT = "SUBSCRIPTION_MANAGEMENT",
  LENDER_DASHBOARD_V2 = "LENDER_DASHBOARD_V2",
  PERSONA_KYC_V1 = "PERSONA_KYC_V1",
  LENDER_DASHBOARD_V2_DUMMY_DATA = "LENDER_DASHBOARD_V2_DUMMY_DATA",
  DOWNLOAD_CSV_AND_JSON_SUMMARY = "DOWNLOAD_CSV_AND_JSON_SUMMARY",
  REVIEW_APPLICATION_STEP = "REVIEW_APPLICATION_STEP",
  BANK_ACCOUNT_CONNECTION_V2 = "BANK_ACCOUNT_CONNECTION_V2",
  IDENTITY_VERIFICATION_SECTION_VIEW = "IDENTITY_VERIFICATION_SECTION_VIEW"
}
