export const QUERY_KEY = {
  GET_FINANCIAL_PROJECTION_SCENARIOS: "GET_FINANCIAL_PROJECTION_SCENARIOS",
  FINANCIAL_COMPANY: "FINANCIAL_COMPANY",
  FINANCIAL_DIRECT_COSTS: "FINANCIAL_DIRECT_COSTS",
  TRANSACTIONAL_MARKETPLACE_REVENUE: "TRANSACTIONAL_MARKETPLACE_REVENUE",
  TRANSACTIONAL_MARKETPLACE_REVENUE_LIST:
    "TRANSACTIONAL_MARKETPLACE_REVENUE_LIST",
  SAAS_REVENUE: "SAAS_REVENUE",
  SAAS_REVENUE_LIST: "SAAS_REVENUE_LIST",
  RECURRING_CHARGE: "RECURRING_CHARGE",
  RECURRING_CHARGES_LIST: "RECURRING_CHARGES_LIST",
  GET_EXPENSE_PEOPLE_FORM: "GET_EXPENSE_PEOPLE_FORM",
  GET_OPERATING_EXPENSES_FORM: "GET_OPERATING_EXPENSES_FORM",
  GET_EXPENSE_TAX_RATE_FORM: "GET_EXPENSE_TAX_RATE_FORM",
  GET_DIRECT_COSTS_FORM: "GET_DIRECT_COSTS_FORM"
}
