export const QUERY_KEY = {
  GET_EXPENSE_PEOPLE_FORM: "GET_EXPENSE_PEOPLE_FORM",
  GET_FP_OPERATING_EXPENSES_FORM: "GET_FP_OPERATING_EXPENSES_FORM",
  GET_EXPENSE_TAX_RATE_FORM: "GET_EXPENSE_TAX_RATE_FORM",
  GET_DIRECT_COSTS_FORM: "GET_DIRECT_COSTS_FORM",
  GET_EQUITY_FINANCING_FORM: "GET_EQUITY_FINANCING_FORM",
  GET_CURRENT_ASSETS_FORM: "GET_CURRENT_ASSETS_FORM",
  GET_LONG_TERM_ASSETS_FORM: "GET_LONG_TERM_ASSETS_FORM",
  GET_REVENUE: "GET_REVENUE",
  GET_FP_DEBT_FINANCING_FORM: "GET_FP_DEBT_FINANCING_FORM",
  GET_FP_DEBT_FINANCING_LIABILITY_FORM: "GET_FP_DEBT_FINANCING_LIABILITY_FORM",
  GET_FINANCIAL_STATEMENT_FORM: "GET_FINANCIAL_STATEMENT_FORM",
  GET_FORECAST_DATA: "GET_FORECAST_DATA",
  GET_LOANREADY_SUBSCRIPTION_BY_PAYMENT_TRANSACTION_ID:
    "GET_LOANREADY_SUBSCRIPTION_BY_PAYMENT_TRANSACTION_ID",
  GET_LOANREADY_SUBSCRIPTION_BY_APPLICATION_ID:
    "GET_LOANREADY_SUBSCRIPTION_BY_APPLICATION_ID",
  GET_UNUSED_LOANREADY_SUBSCRIPTIONS: "GET_UNUSED_LOANREADY_SUBSCRIPTIONS"
}
