export const QUERY_KEY = {
  GET_INCOME_CATEGORIES: "GET_INCOME_CATEGORIES",
  GET_LOAN_PROGRAMS: "GET_LOAN_PROGRAMS",
  GET_LOAN_PROGRAM_DETAILS: "GET_LOAN_PROGRAM_DETAILS",
  GET_LOAN_APPLICATIONS: "GET_LOAN_APPLICATIONS",
  GET_KYB_FORM: "GET_KYB_FORM",
  GET_KYC_FORM: "GET_KYC_FORM",
  GET_FINANCIAL_FORM: "GET_FINANCIAL_FORM",
  GET_CONFIRMATION_FORM: "GET_CONFIRMATION_FORM",
  GET_USER_LOAN_APPLICATION_DETAILS: "GET_USER_LOAN_APPLICATION_DETAILS",
  GET_FORM_DOCUMENTS: "GET_FORM_DOCUMENTS",
  GET_DOWNLOAD_DOCUMENT: "GET_DOWNLOAD_DOCUMENT"
}
