export const QUERY_KEY = {
  GET_INCOME_CATEGORIES: "GET_INCOME_CATEGORIES",
  GET_LOAN_PROGRAMS: "GET_LOAN_PROGRAMS",
  GET_LOAN_PROGRAM_DETAILS: "GET_LOAN_PROGRAM_DETAILS",
  GET_KYB_FORM: "GET_KYB_FORM",
  GET_KYC_FORM: "GET_KYC_FORM",
  GET_FINANCIAL_FORM: "GET_FINANCIAL_FORM",
  GET_CONFIRMATION_FORM: "GET_CONFIRMATION_FORM",
  GET_FORM_DOCUMENTS: "GET_FORM_DOCUMENTS",
  GET_DOWNLOAD_DOCUMENT: "GET_DOWNLOAD_DOCUMENT",
  GET_LOAN_APPLICATION_CASHFLOW_VERIFICATION:
    "GET_LOAN_APPLICATION_CASHFLOW_VERIFICATION",
  GET_CURRENT_LOANS_FORM: "GET_CURRENT_LOANS_FORM",
  GET_OPERATING_EXPENSES_FORM: "GET_OPERATING_EXPENSES_FORM",
  GET_IDENTITY_VERIFICATION: "GET_IDENTITY_VERIFICATION",
  GET_PLAID_ITEM_IDS: "GET_PLAID_ITEM_IDS",
  GET_PLAID_CONNECTED_BANK_ACCOUNTS_BY_APPLICATION_ID:
    "GET_PLAID_CONNECTED_BANK_ACCOUNTS_BY_APPLICATION_ID"
}
