import { ExportFPOption } from "../components/store/fp-helpers"

const getDisclaimerNoteContent = (noteKeys: ExportFPOption[] = []) => {
  const isForecasts = noteKeys.some((key) =>
    [
      ExportFPOption.CASH_FLOW_FORECAST,
      ExportFPOption.BALANCE_SHEET_FORECAST,
      ExportFPOption.INCOME_SHEET_FORECAST
    ].includes(key)
  )
  const isFinancials = noteKeys.some((key) =>
    [
      ExportFPOption.CASH_FLOW,
      ExportFPOption.BALANCE_SHEET,
      ExportFPOption.INCOME_SHEET
    ].includes(key)
  )
  const isLoanReady = noteKeys.includes(ExportFPOption.LOAN_READY_SECTION)
  const isApplicationSummary = noteKeys.includes(
    ExportFPOption.APPLICATION_SUMMARY
  )

  if (
    checkBooleanArray({
      trueValues: [isApplicationSummary],
      falseValues: [isFinancials, isForecasts, isLoanReady]
    })
  ) {
    // Application only
    return [
      `This application is generated based on user inputs, data retrieved from banking sources, and other third-party data providers. All information is provided "as is," with no guarantees of completeness, accuracy, or timeliness. We are not responsible for any errors or omissions in the information or for the results obtained from its use. `,
      `Our platform incorporates third-party data, and while we strive to ensure its accuracy, we do not assume any responsibility for inaccuracies or delays from external data providers. Users are encouraged to consult a financial professional before making decisions based on the projections generated by this application.`,
      `We take the privacy of your data seriously. Please refer to our Privacy Policy for details on how your information is collected and used. By utilizing this application, you acknowledge and agree to these terms.`
    ]
  } else if (
    checkBooleanArray({
      trueValues: [isLoanReady],
      falseValues: [isApplicationSummary, isFinancials, isForecasts]
    })
  ) {
    // Loan Ready only
    return [
      `This assessment is generated based on user inputs, data retrieved from banking sources, and other third-party data providers. All information is provided "as is," with no guarantees of completeness, accuracy, or timeliness. We are not responsible for any errors or omissions in the information or for the results obtained from its use.`,
      `Our platform incorporates third-party data, and while we strive to ensure its accuracy, we do not assume any responsibility for inaccuracies or delays from external data providers. Users are encouraged to consult a financial professional before making decisions based on the analysis generated by this application.`,
      `We take the privacy of your data seriously. Please refer to our Privacy Policy for details on how your information is collected and used. By utilizing this assessment, you acknowledge and agree to these terms.`
    ]
  } else if (
    checkBooleanArray({
      trueValues: [isApplicationSummary, isLoanReady],
      falseValues: [isFinancials, isForecasts]
    })
  ) {
    return [
      // Application + Loan Ready
      `This assessment is generated based on user inputs, data retrieved from banking sources, and other third-party data providers. All information is provided "as is," with no guarantees of completeness, accuracy, or timeliness. We are not responsible for any errors or omissions in the information or for the results obtained from its use. `,
      `Our platform incorporates third-party data, and while we strive to ensure its accuracy, we do not assume any responsibility for inaccuracies or delays from external data providers. Users are encouraged to consult a financial professional before making decisions based on the analysis generated by this application.`,
      `We take the privacy of your data seriously. Please refer to our Privacy Policy for details on how your information is collected and used. By utilizing this assessment, you acknowledge and agree to these terms.`
    ]
  } else if (
    checkBooleanArray({
      trueValues: [isApplicationSummary, isFinancials, isLoanReady],
      falseValues: [isForecasts]
    })
  ) {
    // Application + Financials +  Loan Ready
    return [
      `The projections and financial statements provided in this application are generated based on user inputs, data retrieved from banking sources, and other third-party data providers. Please be advised that these projections are forward-looking and subject to uncertainties. Actual results may differ materially from the projections provided, and no guarantee of future performance is implied.`,
      `All information is provided "as is," with no guarantees of completeness, accuracy, or timeliness. We are not responsible for any errors or omissions in the information or for the results obtained from its use. The financial projections are estimates and should be used as planning tools rather than definitive representations of your financial future.`,
      `Our platform incorporates third-party data, and while we strive to ensure its accuracy, we do not assume any responsibility for inaccuracies or delays from external data providers. Users are encouraged to consult a financial professional before making decisions based on the projections generated by this application.`,
      `We take the privacy of your data seriously. Please refer to our Privacy Policy for details on how your information is collected and used. By utilizing this application, you acknowledge and agree to these terms.`
    ]
  } else if (
    checkBooleanArray({
      trueValues: [isFinancials],
      falseValues: [isForecasts, isLoanReady, isApplicationSummary]
    })
  ) {
    // Financials only
    return [
      `The projections and financial statements provided are generated based on user inputs, data retrieved from banking sources and other third-party data providers. Please be advised that these projections are forward-looking and subject to uncertainties. Actual results may differ materially from the projections provided, and no guarantee of future performance is implied.`,
      `All information is provided "as is," with no guarantees of completeness, accuracy, or timeliness. We are not responsible for any errors or omissions in the information or for the results obtained from its use. The financial projections are estimates and should be used as planning tools rather than definitive representations of your financial future.`,
      `Our platform incorporates third-party data, and while we strive to ensure its accuracy, we do not assume any responsibility for inaccuracies or delays from external data providers. Users are encouraged to consult a financial professional before making decisions based on the projections generated by this application.`,
      `We take the privacy of your data seriously. Please refer to our Privacy Policy for details on how your information is collected and used. By utilizing this application, you acknowledge and agree to these terms.`
    ]
  } else if (
    checkBooleanArray({
      trueValues: [isForecasts, isLoanReady],
      falseValues: [isFinancials, isApplicationSummary]
    })
    // Forecasts + Loan Ready
  ) {
    return [
      `The projections and financial statements provided in this application are generated based on user inputs, data retrieved from banking sources, and other third-party data providers. Please be advised that these projections are forward-looking and subject to uncertainties. Actual results may differ materially from the projections provided, and no guarantee of future performance is implied.`,
      `All information is provided "as is," with no guarantees of completeness, accuracy, or timeliness. We are not responsible for any errors or omissions in the information or for the results obtained from its use. The financial projections are estimates and should be used as planning tools rather than definitive representations of your financial future.`,
      `Our platform incorporates third-party data, and while we strive to ensure its accuracy, we do not assume any responsibility for inaccuracies or delays from external data providers. Users are encouraged to consult a financial professional before making decisions based on the projections generated by this application.`,
      `We take the privacy of your data seriously. Please refer to our Privacy Policy for details on how your information is collected and used. By utilizing this application, you acknowledge and agree to these terms.`
    ]
  }

  // All other cases
  return [
    `The projections and financial statements provided in this
    application are generated based on user inputs, data retrieved from
    banking sources, and other third-party data providers. Please be
    advised that these projections are forward-looking and subject to
    uncertainties. Actual results may differ materially from the
    projections provided, and no guarantee of future performance is
    implied.`,

    `All information is provided "as is," with no guarantees of
    completeness, accuracy, or timeliness. We are not responsible for
    any errors or omissions in the information or for the results
    obtained from its use. The financial projections are estimates and
    should be used as planning tools rather than definitive
    representations of your financial future.`,

    `Our platform incorporates third-party data, and while we strive to
    ensure its accuracy, we do not assume any responsibility for
    inaccuracies or delays from external data providers. Users are
    encouraged to consult a financial professional before making
    decisions based on the projections generated by this application.`,

    `We take the privacy of your data seriously. Please refer to our
    Privacy Policy for details on how your information is collected and
    used. By using this application, you acknowledge and agree to these
    terms.`
  ]
}

const checkBooleanArray = ({
  trueValues,
  falseValues
}: {
  trueValues: boolean[]
  falseValues: boolean[]
}) => {
  return (
    trueValues.every((value) => value) && falseValues.every((value) => !value)
  )
}

export { getDisclaimerNoteContent }
