export const QUERY_KEY = {
  GET_LOAN_APPLICATION_KYB: "GET_LOAN_APPLICATION_KYB",
  GET_LOAN_APPLICATION_KYC: "GET_LOAN_APPLICATION_KYC",
  GET_DOCUMENT_DETAILS: "GET_DOCUMENT_DETAILS",
  GET_DOCUMENT_VISUALIZATIONS: "GET_DOCUMENT_VISUALIZATIONS",
  GET_LOAN_APPLICATION_DETAILS: "GET_LOAN_APPLICATION_DETAILS"
}
