export const QUERY_KEY = {
  GET_LOAN_APPLICATION_KYB: "GET_LOAN_APPLICATION_KYB",
  GET_LOAN_APPLICATION_KYC: "GET_LOAN_APPLICATION_KYC",
  GET_DOCUMENT_DETAILS: "GET_DOCUMENT_DETAILS",
  GET_DOCUMENT_VISUALIZATIONS: "GET_DOCUMENT_VISUALIZATIONS",
  GET_LOAN_APPLICATION_DETAILS: "GET_LOAN_APPLICATION_DETAILS",
  GET_LOAN_SUMMARY: "GET_LOAN_SUMMARY",
  GET_LOAN_SUMMARY_DOWNLOAD: "GET_LOAN_SUMMARY_DOWNLOAD",
  GET_DOCUMENT_DOWNLOAD: "GET_DOCUMENT_DOWNLOAD",
  GET_CASH_FLOW_ANALYSIS: "GET_CASH_FLOW_ANALYSIS",
  GET_BANK_ACCOUNTS: "GET_BANK_ACCOUNTS",
  GET_LOAN_PROGRAM_LIST: "GET_LOAN_PROGRAM_LIST"
}
