name: Create Major Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: 'write'

    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: github-app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ steps.github-app-token.outputs.token }}
          persist-credentials: false
      - name: Bump version
        run: |
          git config user.email github-actions@github.com
          git config user.name github-actions
          ./tools/create_release.sh major
